spring.application.name=unicauca-asst

spring.datasource.url=jdbc:postgresql://localhost:5432/db_asst
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.open-in-view=false

# ===== Google OAuth =====
spring.security.oauth2.client.registration.google.client-id=611422532123-5d08k8boi712dtirdd14gsdrpt7f4km0.apps.googleusercontent.com
google.allowed-domain=unicauca.edu.co

# ===== JWT =====
jwt.secret=dzFlUziAshAOC3IYDb9URcBn4lx8T3yh20EdrbAKokQkRjxL0mQaa/lify7hSQd9tj1xeuSDSJFAjLgEYnM8GQ==
jwt.access-token.expiration=3600000
jwt.refresh-token.expiration=86400000

# ===== Spring Security =====
spring.thymeleaf.check-template-location=false

# ===== Thymeleaf =====
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false