MERGE INTO estados_usuario (id, nombre) VALUES (1, 'Activo');
MERGE INTO roles (id, nombre, nombre_clave) VALUES (1, 'Profesional ASST', 'PROFESIONAL_ASST');
MERGE INTO roles (id, nombre, nombre_clave) VALUES (2, 'Administrador', 'ADMIN');
MERGE INTO usuarios_sistema (id, correo_electronico, nombre_usuario, nombre_completo, fecha_registro, estado_usuario_id, fecha_creacion) VALUES (1, 'admin@unicauca.edu.co', 'admin_test', 'Admin Test', TIMESTAMP '2024-01-01 00:00:00', 1, TIMESTAMP '2024-01-01 00:00:00');
ALTER TABLE usuarios_sistema ALTER COLUMN id RESTART WITH 100;
MERGE INTO usuarios_sistema_roles (usuario_sistema_id, rol_id) KEY (usuario_sistema_id, rol_id) VALUES (1, 2);
MERGE INTO tipos_identificacion (id_tipo_identificacion, nombre, abreviatura) VALUES (1, 'Cedula de Ciudadania', 'CC');
MERGE INTO estados_persona_evaluada (id_estado_persona_evaluada, nombre) VALUES (1, 'Sin registro');
MERGE INTO estados_persona_evaluada (id_estado_persona_evaluada, nombre) VALUES (2, 'Con registro');
MERGE INTO estados_registro_gestion_baterias (id_estado_registro_gestion_bateria, nombre) VALUES (1, 'Creado');
